set MATLAB=D:\MATLAB\R2018a
"%MATLAB%\bin\%MATLAB_WIN_VER%\gmake" -f LED_13.mk  GENERATE_ASAP2=0 DOWNLOADAPPLICATION=1 STM32CUBEMXPATHUPDATE=1 STM32CUBEMXPATH="C:\Program Files (x86)\STMicroelectronics\STM32Cube\STM32CubeMX" TARGET_INST_FULLPATH="D:\MATLAB\STM32-MAT\STM32" IOC_FULLPATH=".\LED_13.ioc" IT_HANDLER_OPTIM=1 ISPROTECTINGMODEL=NOTPROTECTING STANDALONE_SUPPRESS_EXE=1
